# Site settings
name: 邵文
location: 石家庄
company: 石家庄铁道大学
position: 软件设计师
github: https://github.com/shaowens
facebook: https://www.facebook.com/
phone: 1863733XXXX
email: 2698547773@qq.com

baseurl: ""

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

